// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusalaSoft.GatewayApi.Data;

namespace GatewayApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210527173958_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MusalaSoft.GatewayApi.Model.Device", b =>
                {
                    b.Property<int>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Online")
                        .HasColumnType("bit");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gatewayUSN")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UID");

                    b.HasIndex("gatewayUSN");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("MusalaSoft.GatewayApi.Model.Gateway", b =>
                {
                    b.Property<string>("USN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USN");

                    b.ToTable("gateways");
                });

            modelBuilder.Entity("MusalaSoft.GatewayApi.Model.Device", b =>
                {
                    b.HasOne("MusalaSoft.GatewayApi.Model.Gateway", "gateway")
                        .WithMany("Devices")
                        .HasForeignKey("gatewayUSN");

                    b.Navigation("gateway");
                });

            modelBuilder.Entity("MusalaSoft.GatewayApi.Model.Gateway", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
